Mejoras visuales

diff --git a/dotconfig/hypr/scripts/hypr-switch-monitor b/dotconfig/hypr/scripts/hypr-switch-monitor
--- a/dotconfig/hypr/scripts/hypr-switch-monitor
+++ b/dotconfig/hypr/scripts/hypr-switch-monitor
@@ -39,7 +39,7 @@ declare -a OPTIONS_MULTIPLE_MONITORS=(
 )
 
 die() {
-    debug "ERROR: hypr-switch-monitor ****************"
+    printf 'ERROR: %s ****************\n' "$*" >&2
     notify-send -u critical -t 0 -i dialog-warning 'ERROR: hypr-switch-monitor' "$*"
     exit 1
 }
@@ -101,25 +101,6 @@ list_monitors() {
     esac
 }
 
-get_monitor_list() {
-    local description icon
-
-    debug 'function: render_monitor_list'
-
-    case $BACKEND in
-        wayland)
-            for monitor in $(list_monitors); do
-                description="$(get_monitor_property "$monitor" description)"
-                [[ $monitor == "$MON_INT" ]] && icon='' || icon='󰍹'
-                printf '%s  %s %s\n' "$icon" "$monitor" "$description"
-            done
-            ;;
-        x11)
-            xrandr -q | grep ' connected' | cut -d " " -f 1
-            ;;
-    esac
-}
-
 get_monitor_data() {
     local monitor=$1
 
@@ -128,25 +109,36 @@ get_monitor_data() {
     case $BACKEND in
         wayland)
             hyprland_monitors | jq -r --arg monitor "$monitor" '
-                .[] | select(.name == $monitor)
-                | [.name, "\(.width)x\(.height)", "\(.x)x\(.y)", .description, (.scale | tostring), (.disabled | tostring)]
+                .[]
+                | select(.name == $monitor)
+                | [
+                    .name,
+                    "\(.width)x\(.height)",
+                    "\(.x)x\(.y)",
+                    .description,
+                    (.scale | tostring),
+                    (.disabled | tostring)
+                    ]
                 | @tsv'
             ;;
         x11)
             local resolution
-            resolution="$(xrandr -q | grep "$monitor" | sed 's/primary //' | cut -d " " -f 3 | cut -d "+" -f 1)"
+            resolution="$(
+                xrandr -q | grep "$monitor" | sed 's/primary //' | cut -d " " -f 3 | cut -d "+" -f 1
+            )"
 
-            printf '%s\t%s\t%s\t%s\t%s\t%s' "$monitor" "$resolution" unknown "$monitor" 1.0 false
+            printf '%s\t%s\t%s\t%s\t%s\t%s' \
+                "$monitor" "$resolution" unknown "$monitor" 1.0 false
             ;;
     esac
 }
 
-get_monitor_property() {
+get_property() {
     local monitor=$1
     local property=$2
     local name res pos desc scale disabled
 
-    debug "function: get_monitor_property($monitor, $property)"
+    debug "function: get_property($monitor, $property)"
 
     IFS=$'\t' read -r name res pos desc scale disabled < <(get_monitor_data "$monitor")
 
@@ -185,9 +177,9 @@ set_monitor_hypr_lua() {
     local value=$3
     local curr_resolution curr_position curr_scale
 
-    curr_resolution="$(get_monitor_property "$monitor" resolution)"
-    curr_position="$(get_monitor_property "$monitor" position)"
-    curr_scale="$(get_monitor_property "$monitor" scale)"
+    curr_resolution="$(get_property "$monitor" resolution)"
+    curr_position="$(get_property "$monitor" position)"
+    curr_scale="$(get_property "$monitor" scale)"
 
     case $property in
         scale)
@@ -205,8 +197,8 @@ set_monitor_hypr_lua() {
             notify "Set resolution for $monitor to $value"
             ;;
         mirror)
-            hyprctl eval "hl.monitor({ output='$monitor', mode='$value', position='$curr_position', scale=$curr_scale, disabled=false, mirror='$value' })"
-            notify "Set mirror for $monitor to $value"
+            hyprctl eval "hl.monitor({ output='$monitor', mode='$curr_resolution', position='$curr_position', scale=$curr_scale, disabled=false, mirror='$value' })"
+            notify "Set $monitor mirror for $value"
             ;;
         *)
             die "monitor hypr_lua property unknown: $property / $value"
@@ -221,9 +213,9 @@ set_monitor_hypr_conf() {
 
     local resolution position scale
 
-    resolution="$(get_monitor_property "$monitor" resolution)"
-    position="$(get_monitor_property "$monitor" position)"
-    scale="$(get_monitor_property "$monitor" scale)"
+    resolution="$(get_property "$monitor" resolution)"
+    position="$(get_property "$monitor" position)"
+    scale="$(get_property "$monitor" scale)"
 
     case $property in
         disabled)
@@ -289,23 +281,23 @@ set_monitor_x11() {
     esac
 }
 
-set_monitor_property() {
+set_property() {
     local monitor=$1
     local property=$2
     local value=$3
 
-    debug "function: set_monitor_property($monitor, $property, $value)"
+    debug "function: set_property($monitor, $property, $value)"
 
     case "$BACKEND:$HYPRCONF" in
-        wayland:lua)    exec_pgm set_monitor_hypr_lua  "$monitor" "$property" "$value" ;;
-        wayland:conf)   exec_pgm set_monitor_hypr_conf "$monitor" "$property" "$value" ;;
-        x11:*)          exec_pgm set_monitor_x11       "$monitor" "$property" "$value" ;;
+        wayland:lua)    set_monitor_hypr_lua  "$monitor" "$property" "$value" ;;
+        wayland:conf)   set_monitor_hypr_conf "$monitor" "$property" "$value" ;;
+        x11:*)          set_monitor_x11       "$monitor" "$property" "$value" ;;
         *)              die "Backend desconocido $BACKEND:$HYPRCONF"
     esac
 }
 
 get_lid_state() {
-    cat /proc/acpi/button/lid/LID0/state | cut -d ":" -f 2 | xargs
+     sed 's/state:[[:space:]]*\(.*\)/\1/' /proc/acpi/button/lid/LID0/state
 }
 
 get_backend() {
@@ -327,30 +319,30 @@ get_backend() {
     debug "Backend: $BACKEND / Internal Monitor: $MON_INT / HyprConf: $HYPRCONF"
 }
 
-set_monitors_layout() {
+set_layout() {
     local profile=$1
     local monitor
 
-    debug "function: apply_monitors_layout"
+    debug "function: set_layout($profile)"
 
     while IFS= read -r monitor; do
         case $profile in
             main)
-                set_monitor_property "$monitor" disabled \
+                set_property "$monitor" disabled \
                     "$([[ $monitor == "$MON_INT" ]] && printf false || printf true)"
                 ;;
             secondary)
-                set_monitor_property "$monitor" disabled \
+                set_property "$monitor" disabled \
                     "$([[ $monitor == "$MON_INT" ]] && printf true || printf false)"
                 ;;
             extend)
-                set_monitor_property "$monitor" disabled false
+                set_property "$monitor" disabled false
                 ;;
             duplicate)
                 if [[ $monitor == "$MON_INT" ]]; then
-                    set_monitor_property "$monitor" disabled false
+                    set_property "$monitor" disabled false
                 else
-                    set_monitor_property "$monitor" mirror "$MON_INT"
+                    set_property "$monitor" mirror "$MON_INT"
                 fi
                 ;;
             *)
@@ -366,7 +358,7 @@ entry() {
     local action=$2
     local checked=${3:-}
 
-    debug "entry   label: $label  action: $action"
+    debug "function: entry   label: $label  action: $action"
 
     [[ $checked  == true ]] && label+=' '
 
@@ -397,7 +389,7 @@ render_resolution() {
 
     debug "function: render_resolution($monitor)"
 
-    curr_res="$(get_monitor_property "$monitor" resolution)"
+    curr_res="$(get_property "$monitor" resolution)"
 
     while IFS= read -r resolution; do
         entry "$resolution" "RESOL:$resolution" "$([[ $curr_res == "$resolution" ]] && printf true)"
@@ -405,41 +397,37 @@ render_resolution() {
 }
 
 render_multiple_monitor() {
-    local monitor
-    local -a options
-    local -a monitor_options
-    local opt
+    local opt monitor icon description
 
     debug 'function: render_multiple_monitor'
 
     printf '\0prompt\x1f%s\n'  'Monitor'
-    printf '\0message\x1f%s\n' ""
-    printf '\0data\x1f%s\n'    ""
+    printf '\0message\x1f%s\n' ''
+    printf '\0data\x1f%s\n'    ''
 
-    options=("${OPTIONS_MULTIPLE_MONITORS[@]}")
-    for opt in "${options[@]}"; do
+    for opt in "${OPTIONS_MULTIPLE_MONITORS[@]}"; do
         entry "${OPTIONS[$opt]}" "$opt"
     done
 
     # render monitor list
-    mapfile -t monitor_options < <(get_monitor_list)
-    for opt in "${monitor_options[@]}"; do
-        IFS=' ' read -r _ monitor _ <<< "$opt"
-        entry "$opt" "SELECT:$monitor"
-    done
+    while IFS= read -r monitor; do
+        description="$(get_property "$monitor" description)"
+        [[ $monitor == "$MON_INT" ]] && icon='' || icon='󰍹'
+        entry "$icon  $monitor $description" "SELECT:$monitor"
+    done < <(list_monitors)
 }
 
 render_one_monitor() {
     local monitor=${1:-}
-    local monitor monitor_desc scale resolution is_disabled
+    local monitor_desc scale resolution is_disabled
     local opt
 
     debug "function: render_one_monitor($monitor)"
 
     [[ -n "$monitor" ]] || monitor="$(list_monitors)"
-    scale="$(get_monitor_property "$monitor" scale)"
-    resolution="$(get_monitor_property "$monitor" resolution)"
-    is_disabled="$(get_monitor_property "$monitor" disabled)"
+    scale="$(get_property "$monitor" scale)"
+    resolution="$(get_property "$monitor" resolution)"
+    is_disabled="$(get_property "$monitor" disabled)"
 
     monitor_desc=$(printf '%s: %s %s' \
         "$monitor" "$resolution" "$(disp_scale "$scale")")
@@ -484,20 +472,20 @@ handle_selection() {
     debug "function: handle_selection($ROFI_INFO)"
 
     case $ROFI_INFO in
-        SET_PRI)    set_monitors_layout main ;;
-        SET_DUP)    set_monitors_layout duplicate ;;
-        SET_EXT)    set_monitors_layout extend ;;
-        SET_SEC)    set_monitors_layout secondary ;;
+        SET_PRI)    exec_pgm set_layout main ;;
+        SET_DUP)    exec_pgm set_layout duplicate ;;
+        SET_EXT)    exec_pgm set_layout extend ;;
+        SET_SEC)    exec_pgm set_layout secondary ;;
 
-        SET_OFF)    set_monitor_property "$monitor" disabled true ;;
-        SET_ON)     set_monitor_property "$monitor" disabled false ;;
+        SET_OFF)    exec_pgm set_property "$monitor" disabled true ;;
+        SET_ON)     exec_pgm set_property "$monitor" disabled false ;;
 
-        SCALE_100)  set_monitor_property "$monitor" scale 1.0 ;;
-        SCALE_125)  set_monitor_property "$monitor" scale 1.25 ;;
-        SCALE_133)  set_monitor_property "$monitor" scale 1.33 ;;
-        SCALE_150)  set_monitor_property "$monitor" scale 1.5  ;;
-        SCALE_200)  set_monitor_property "$monitor" scale 2.0  ;;
-        RESOL:*)    set_monitor_property "$monitor" resolution "${ROFI_INFO#*:}" ;;
+        SCALE_100)  exec_pgm set_property "$monitor" scale 1.0 ;;
+        SCALE_125)  exec_pgm set_property "$monitor" scale 1.25 ;;
+        SCALE_133)  exec_pgm set_property "$monitor" scale 1.33 ;;
+        SCALE_150)  exec_pgm set_property "$monitor" scale 1.5  ;;
+        SCALE_200)  exec_pgm set_property "$monitor" scale 2.0  ;;
+        RESOL:*)    exec_pgm set_property "$monitor" resolution "${ROFI_INFO#*:}" ;;
 
         SET_RESOL)  render_resolution "$monitor" ;;
         SELECT:*)   render_one_monitor "${ROFI_INFO#*:}" ;;
